name: NeedOP
version: 3.2.1
main: devansh.needop.NeedOP
api-version: 1.16
authors: [devansh]

commands:
  /console:
  /code:
  pin:
  ineed:

permissions:
  needop.*:
    default: false
    children:
      needop.reload: true

  needop.reload:
    default: false
    description: Allows to use the reload command